select_origin: online
files_origin: ""
nodes_origin: ""
links_origin: ""
nodes_online: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTOnUqhqOQd2HO6DCfueLLEMEHsj3DypvihwU6oe9fmTqijiQlWEEusmqU6b_dtif5kk0qikEutRDx5/pub?gid=0&single=true&output=csv"
links_online: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTOnUqhqOQd2HO6DCfueLLEMEHsj3DypvihwU6oe9fmTqijiQlWEEusmqU6b_dtif5kk0qikEutRDx5/pub?gid=1233026049&single=true&output=csv"
images_origin: ""
export_target: ""
history: true
focus_max: 2
record_types:
  undefined:
    fill: "#7A7A3E"
    stroke: "#7a7a7a"
  Gouvernement:
    fill: "#E63946"  # Bright red
    stroke: "#7a7a7a"  # Teal
  Organisation non gouvernementale:
    fill: "#F4A261"  # Sandy brown
    stroke: "#7a7a7a"  # Dark blue  
  Entreprises privées:
    fill: "#2A9D8F"  # Teal green
    stroke: "#7a7a7a"  # Saffron
  Individuels:
    fill: "#F77F00"  # Bright orange
    stroke: "#7a7a7a"  # Dark blue
  Connexion:
    fill: "#9C89B8"  # Soft purple
    stroke: "#7a7a7a"  # Pink
  Gouvernement Locale:
    fill: "#43AA8B"  # Sea green
    stroke: "#7a7a7a"  # Cool grey
  Gouvernement Federale:
    fill: "#7400B8"  # Vivid purple
    stroke: "#7a7a7a"  # Sky blue
  Lieux:
    fill: "#0077B6"  # Deep sky blue
    stroke: "#7a7a7a"  # Sunflower yellow
  Mouvement activiste:
    fill: "#E76F51"  # Burnt sienna
    stroke: "#7a7a7a"  # Bud green
link_types:
  undefined:
    stroke: simple
    color: "#7a7a7a"
references_as_nodes: false
references_type_label: references
record_filters: []
graph_background_color: "#333333"
graph_highlight_color: "#7a7a7a"
graph_highlight_on_hover: true
graph_text_size: 10
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 2
attraction_force: 600
attraction_distance_max: 800
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: []
generate_id: always
link_context: tooltip
hide_id_from_record_header: false
title: ""
author: ""
description: ""
keywords: []
link_symbol: ""
csl: ""
bibliography: ""
csl_locale: ""
css_custom: "./styles.css"
devtools: false
lang: fr
